const questions = [
    {
        
        question: 'WHAT IS THE FULL FORM OF HYSD BAR?',
        options: ['HIGH YIELD STRENGTH DEFORMATION BAR',
            'HIGHEST YIELD STRENGTH DEFORMED BAR',
            'HIGHER YIELD STREE DEFORMATION BAR',
            'NONE OF THESE'],
        correctAnswer: 0,
    },
    {
        
        question: 'DEVELOPMENT OF THE PRISMS WILL BE',
        options: ['RECTANGLE',
            'N0. OF SQUARES',
            'N0. OF RECTANGLES',
            'SQUARES'],
        correctAnswer: 2,
    },
    {
        id:'3',
        question: 'FULL FORM OF BIS',
        options: ['BEST INDIAN STANDARD',
            'BOARD OF INDIAN STANDARD',
            'BUREAUE OF INDIAN STANDARD',
            'NONE OF THESE'],
        correctAnswer: 2,
    },
    {
        id:'4',
        question: 'THE SIZE OF THE DRAWING DRAWN TO SCALE 2:1 WILL BE ____________ THE ACTUAL SIZE.',
        options: ['SAME AS',
            'TWICE OF',
            'HALF OF',
            'NONE OF A, B, AND C'],
        correctAnswer: 1,
    },
    
    {
        id:'5',
        question: 'IN THE ORTHOGRAPHIC PROJECTIONS, F.V. IS PROJECTED ON',
        options: ['H.P',
            'V.P',
            'XY',
            'GL'],
        correctAnswer: 1,
    },
    {
        id:'6',
        question: 'WHEN THE DRAWING ARE DRAWN LARGER THAN THE ACTUAL SIZE OF OBJECT THEN SCALE IS KNOWN AS',
        options: ['ENLARGED SCALE',
            'REDUCED SCALE',
            'FULL SCALE',
            'STANDARD SCALE'],
        correctAnswer: 0,
    },
    {
        id:'7',
        question: 'A SPHERE CAN BE DESCRIBED IN HOW MANY VIEWS?',
        options: ['4',
            '3',
            '2',
            '1'],
        correctAnswer: 3,
    },
    {
        id:'8',
        question: 'IF POINT "C" IS BELOW HP AND BEHIND VP THEN IN WHICH QUADRANT POINT "C" LIES?',
        options: ['FIRST',
            'SECOND',
            'THIRD',
            'FOURTH'],
        correctAnswer: 2,
    },
    {
        id:'9',
        question: 'WHEN A POINT IS BELOW HP & IN FRONT OF VP IT IS IN',
        options: ['FIRST QUADRANT',
            'SECOND QUADRANT',
            'THIRD QUADRANT',
            'FOURTH QUADRANT'],
        correctAnswer: 3,
    },
    {
        id:'10',
        question: 'IN ISOMETRIC VIEW LENGTH, WIDTH, AND HEIGHT ARE INCLINED AT',
        options: ['30',
                  '60',
                  '90',
                  '120'],
        correctAnswer: 3,
    },
    {
        id:'11',
        question: 'SECOND ANGLE PROJECTION IS NOT USED BECAUSE',
        options: ['PLAN IS ABOVE XY',
            'BOTH VIEWS OVERLAP EACH OTHER',
            'ELEVATION IS ABOVE XY',
            'VIEWS ARE SMALL IN SIZE'],
        correctAnswer: 1,
    },
    {
        id:'12',
        question: 'LENGTH (L) OF LINE IN ISOMETRIC VIEW WILL BE EQUAL TO',
        options: ['0.707 L',
            '0.815 L',
            'TRUE LENGTH L',
            '0.866 L'],
        correctAnswer: 2,
    },
    {
        id:'13',
        question: 'DASHED LINE IS USED TO DRAW',
        options: ['OUTER EDGES',
            'PROJECTIONS',
            'CENTER & CENTER AXIS',
            'HIDDEN FACES'],
        correctAnswer: 3,
    },
    {
        id:'14',
        question: 'A SQUARE PLANE IS INCLINED TO VP & PERPENDICULAR TO HP ITS ELEVATION APPEARS AS',
        options: ['RHOMBUS',
            'SQUARE',
            'STRAIGHT LINE',
            'RECTANGLE'],
        correctAnswer: 2,
    },
    {
        id:'15',
        question: 'IF LINE IS INCLINED TO VERTICAL PLANE AND PARALLEL TO HORIZONTAL PLANE, THEN WHICH ONE OF THE FOLLOWING IS ALWAYS CORRECT?',
        options: ['TRUE LENGTH = PLAN LENGTH',
            'TRUE LENGTH = ELEVATION LENGTH',
            'TRUE LENGTH ≠ PLAN LENGTH',
            'NONE OF THESE'],
        correctAnswer: 0,
    },
    {
        id:'16',
        question: 'IN FIRST ANGLE PROJECTION METHOD THE LEFT HAND SIDE VIEW IS PLACED ON',
        options: ['ABOVE ELEVATION',
            'BELOW ELEVATION',
            'RIGHT SIDE OF F. V. (ELEVATION)',
            'AXONOMETRIC'],
        correctAnswer: 2,
    },
    {
        id:'17',
        question: 'WHICH ONE OF THE FOLLOWING IS NOT A REDUCING SCALE?',
        options: ['1:1',
            '1:200',
            '5:320',
            '5:6'],
        correctAnswer: 0,
    },
    {
        id:'18',
        question: 'WHAT IS THE FULL FORM OF HYSD BAR?',
        options: ['IN FRONT OF V.P. AND ABOVE H.P',
            'BEHIND V.P. AND BELOW H.P',
            'IN FRONT OF V.P. AND BELOW H.P',
            'BEHIND V.P. AND ABOVE H.P'],
        correctAnswer: 3,
    },
    {
        id:'19',
        question: 'WHEN THE DRAWING ARE DRAWN SMALLER THAN THE ACTUAL SIZE OF OBJECT THEN SCALE IS KNOWN AS',
        options: ['REDUCED SCALE',
            'ENLARGED SCALE',
            'FULL SCALE',
            'NONE OF THESE'],
        correctAnswer: 0,
    },
    {
        id:'20',
        question: 'IN A THIRD ANGLE PROJECTION METHOD, RIGHT HAND SIDE VIEW OF AN OBJECT IS DRAWN ___________ FRONT VIEW',
        options: ['LEFT SIDE OF',
            'RIGHT SIDE OF',
            'REAR SIDE OF',
            'NONE OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'21',
        question: 'IF THE 10 M LENGTH IS REPRESENTED AS 1 CM ON THE MAP THEN REPRESENTATIVE FRACTION IS',
        options: ['1/100',
            '1/10',
            '1/1000',
            'NONE OF THE ABOVE'],
        correctAnswer: 2,
    },
    {
        id:'22',
        question: 'FOURTH ANGLE PROJECTION IS NOT USED BECAUSE',
        options: [' FRONT VIEW IS ABOVE REFERENCE LINE AND TOP VIEW IS BELOW REFERENCE LINE',
            'TOP VIEW IS ABOVE REFERENCE LINE AND FRONT VIEW IS BELOW REFERENCE LINE',
            'FRONT VIEW AND TOP VIEW BOTH OVERLAP ON EACH OTHER AND BELOW REFERENCE LINE',
            'FRONT VIEW AND TOP VIEW BOTH OVERLAP ON EACH OTHER AND ABOVE THE REFERENCE LINE'],
        correctAnswer: 2,
    },
    {
        id:'23',
        question: 'FOR THE THIRD ANGLE PROJECTION METHOD, WHICH OF THE FOLLOWING IS CORRECT?',
        options: ['OBSERVER  OBJECT  PLANE',
            'OBSERVER  PLANE  OBJECT',
            '(A) AND (B) BOTH',
            'NONE OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'24',
        question: 'NAME THE SOLID FORMED BY FOUR EQUILATERAL TRIANGLES',
        options: ['SQUARE PYRAMID',
            'TRIANGULAR PYRAMID',
            'TETRAHEDRON',
            'SQUARE PRISM'],
        correctAnswer: 2,
    },
    {
        id:'25',
        question: 'A CYLINDER STANDING ON THE HP IS CUT BY A VERTICAL PLANE PARALLEL TO THE AXIS AND AWAY FROM IT. THE SHAPE OF THE SECTION WILL BE',
        options: ['RECTANGLE',
            'ELLIPSE',
            'PARABOLA',
            'HYPERBOLA'],
        correctAnswer: 0,
    },
    {
        id:'26',
        question: '1FT=________CM',
        options: ['30.48',
            '0.3048',
            '3.28',
            '35.31'],
        correctAnswer: 0,
    },
    {
        id:'27',
        question: '1 KM=_____CM',
        options: ['10000',
            '100000',
            '100',
            '12000'],
        correctAnswer: 1,
    },
    {
        id:'28',
        question: 'THE RATIO OF THE LENGTH OF THE DRAWING OF THE OBJECT TO THE ACTUAL LENGTH OF THE OBJECT IS CALLED _________________',
        options: ['RESULTING FRACTION',
            'REPRESENTATIVE FRACTION',
            'REPRESENTATIVE FACTOR',
            'NONE OF THESE'],
        correctAnswer: 1,
    },
    {
        id:'29',
        question: 'FOR ANGULAR MEASUREMENT WE USE WHICH TYPE OF SCALE?',
        options: ['VERNIER SCALE',
            'ISOMETRIC SCALE',
            'SCALE OF CHORD',
            'NONE OF THESE'],
        correctAnswer: 2,
    },
    {
        id:'30',
        question: 'THE TWO WAYS OF DRAWINGS ORTHOGRAPHIC PROJECTION ARE',
        options: ['FIRST ANGLE, SECOND ANGLE',
            'FIRST ANGLE, THIRD ANGLE',
            'FIRST ANGLE, FOURTH ANGLE',
            'FOURTH ANGLE, SECOND ANGLE'],
        correctAnswer: 1,
    },
    {
        id:'31',
        question: 'THE SEQUENCE FOR THE DIRECTION OF VIEWS (OR LINE OF SIGHT) FOR ANY ORTHOGRAPHIC PROJECTION AS UTILIZED IN THE UNITED STATES IS',
        options: ['EYE OF OBSERVER>PROJECTION PLANE>OBJECT',
            'EYE OF OBSERVER>OBJECT>PROJECTION PLANE',
            'PROJECTION PLANE>OBJECT>EYE OF OBSERVER',
            'PROJECTION PLANE>EYE OF OBSERVER>OBJECT'],
        correctAnswer: 0,
    },
    {
        id:'32',
        question: 'IN WORKING DRAWINGS, THESE SHOW ALL NECESSARY INFORMATION NOT GIVEN DIRECTLY ON THE DRAWING WITH ITS DIMENSIONS AND NOTES',
        options: ['DOCUMENT STRIPS',
            'PORTABLE DOCUMENTS',
            'FORMATTING FORMS',
            'TITLE AND RECORD STRIPS'],
        correctAnswer: 3,
    },
    {
        id:'33',
        question: 'SPHERE IS THE REVOLUTION OF ________________.',
        options: ['RECTANGLE',
            'CIRCLE',
            'SEMI CIRCLE',
            'TRIANGLE'],
        correctAnswer: 2,
    },
    {
        id:'34',
        question: 'PERSPECTIVE PROJECTION IS ESSENTIAL TO HAVE FULL KNOWLEDGE OF',
        options: ['FIRST ANGLE METHOD',
            'THIRD ANGLE METHOD',
            'FOURTH ANGLE METHOD',
            'NONE OF THESE'],
        correctAnswer: 1,
    },
    {
        id:'35',
        question: 'WHEN THE PROJECTORS ARE PARALLEL TO EACH OTHER AND ALSO PERPENDICULAR TO THE PLANE, THE PROJECTION IS CALLED?',
        options: ['ISOMETRIC PROJECTION',
            'ORTHOGRAPHIC PROJECTION',
            'PERSPECTIVE PROJECTION',
            'AXONOMETRIC PROJECTION'],
        correctAnswer: 1,
    },
    {
        id:'36',
        question: 'IN WHICH PROJECTION THE PLANES OF PROJECTION ARE ASSUMED TO BE TRANSPARENT',
        options: ['1ST ANGLE PROJECTION',
            '3RD ANGLE PROJECTION',
            '4TH ANGLE PROJECTION',
            '2ND ANGLE PROJECTION'],
        correctAnswer: 1,
    },
    {
        id:'37',
        question: 'IN WHICH PROJECTION THE OBJECT LIES BETWEEN THE OBSERVER AND THE PLANE OF PROJECTION',
        options: ['1ST ANGLE PROJECTION',
            '3RD ANGLE PROJECTION',
            '4TH ANGLE PROJECTION',
            '2ND ANGLE PROJECTION'],
        correctAnswer: 0,
    },
    {
        id:'38',
        question: 'IN 1ST ANGLE PROJECTION THE OBJECT IS SITUATED IN WHICH QUADRANT?',
        options: ['1ST QUADRANT',
            '2ND QUADRANT',
            '3RD QUADRANT',
            '4TH QUADRANT'],
        correctAnswer: 0,
    },
    {
        id:'39',
        question: 'THE PLANE OF PROJECTION LIES BETWEEN THE OBSERVER AND THE OBJECT',
        options: ['1ST ANGLE PROJECTION',
            '3RD ANGLE PROJECTION',
            '4TH ANGLE PROJECTION',
            '2ND ANGLE PROJECTION'],
        correctAnswer: 1,
    },
    {
        id:'40',
        question: 'THE PLANE OF PROJECTION LIES BETWEEN THE OBSERVER AND THE OBJECT',
        options: ['1ST ANGLE PROJECTION',
            '3RD ANGLE PROJECTION',
            '4TH ANGLE PROJECTION',
            '2ND ANGLE PROJECTION'],
        correctAnswer: 1,
    },
    {
        id:'41',
        question: 'IN AN OBLIQUE PROJECTION ALSO, THERE ARE THREE AXES - A VERTICAL, A HORIZONTAL AND A THIRD,INCLINED AT AN ANGLE OF WITH THE HORIZONTAL.',
        options: ['30° OR 25°',
            '30° OR 45°',
            '35° OR 40°',
            '60° OR 35°'],
        correctAnswer: 1,
    },
    {
        id:'42',
        question: 'WHICH OF THE FOLLOWING IS NOT A PICTORIAL DRAWING?',
        options: ['ISOMETRIC',
            'MULTIVIEW',
            'PERSPECTIVE',
            'AXONOMETRIC'],
        correctAnswer: 1,
    },
    {
        id:'43',
        question: 'WHICH OF THE FOLLOWING PROJECTION METHODS DOES NOT USE PROJECTORS PERPENDICULAR TO THE PLANE OF PROJECTION?',
        options: ['ISOMETRIC',
            'ORTHOGRAPHIC',
            'OBLIQUE',
            'AXONOMETRIC'],
        correctAnswer: 2,
    },
    {
        id:'44',
        question: 'A CIRCLE WILL APPEAR ON AN ISOMETRIC DRAWING AS A (N) __________.',
        options: ['ELLIPSE',
            'CYCLOID',
            'CIRCLE',
            'PARABOLA'],
        correctAnswer: 0,
    },
    {
        id:'45',
        question: 'IN AN OBLIQUE DRAWING, THE PROJECTION RAYS ARE DRAWN____________TO EACH OTHER AND________TO THE PLANE OF PROJECTION.',
        options: ['INCLINED....INCLINED',
            'INCLINED.......PARALLEL',
            'PARALLEL.......INCLINED',
            'PARALLEL.....PARALLEL'],
        correctAnswer: 2,
    },
    {
        id:'46',
        question: 'WHEN THE DRAWING IS DRAWN OF THE SAME SIZE AS THAT OF THE OBJECT, THE SCALE USED IS _______',
        options: ['DIAGONAL SCALE',
            'FULL-SIZE SCALE',
            'VERNIER SCALE',
            'PLAIN SCALE'],
        correctAnswer: 1,
    },
    {
        id:'47',
        question: 'WHICH TYPE OF LINE IS PARTICULAR TO SECTION DRAWINGS?',
        options: ['BREAK LINES',
            'PHANTOM LINES',
            'EXTENSION LINES',
            'CUTTING PLANE LINES'],
        correctAnswer: 3,
    },
    {
        id:'48',
        question: 'WHICH TYPE OF LINE IS PART OF A DIMENSION?',
        options: ['BREAK LINES',
        'PHANTOM LINES',
        'EXTENSION LINES',
        'CUTTING PLANE LINES'],
    correctAnswer: 2,
    },
    {
        id:'49',
        question: 'IN AN AXONOMETRIC DRAWING, THE PROJECTION RAYS ARE DRAWN______TO EACH OTHER AND ______ TO THE PLANE OF PROJECTION.',
        options: ['PARRLLEL.....OBLIQUE',
            'OBLIQUE.....PARALLEL',
            'PARALLEL....PERPENDICULAR',
            'PARALLEL.....PARALLEL'],
        correctAnswer: 2,
    },
    {
        id:'50',
        question: 'IN WHICH PROJECTION METHOD THE PLANE OF PROJECTION IS ASSUMED NON-TRANSPARENT?',
        options: ['FIRST ANGLE PROJECTION METHOD',
            'SECOND ANGLE PROJECTION METHOD',
            'THIRD ANGLE PROJECTION METHOD',
            'BOTH FIRST ANGLE AND THIRD ANGLE PROJECTION METHOD'],
        correctAnswer: 3,
    },
    {
        id:'51',
        question: 'IMAGINE AN "L" SHAPED FACE EXTRUDED INTO THREE DIMENSIONS. HOW MANY FACES DOES IT CONTAIN?',
        options: ['SEVEN',
            'EIGHT',
            'TEN',
            'SIX'],
        correctAnswer: 1,
    },
    {
        id:'52',
        question: 'THE POINT, FROM WHICH THE OBSERVER IS ASSUMED TO VIEW THE OBJECT, IS CALLED',
        options: ['CENTER OF PROJECTION',
            'POINT OF PROJECTION',
            'POINT OF OBSERVER',
            'VIEW POINT'],
        correctAnswer: 0,
    },
    {
        id:'53',
        question: 'IN THE TERM ORTHO-GRAPHIC, "ORTHOS" MEANS',
        options: ['DRAWING',
            'STRAIGHT',
            'PROJECTION',
            'VIEW'],
        correctAnswer: 1,
    },
    {
        id:'54',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 2,
    },
    {
        id:'55',
        question: 'CENTER LINE IS',
        options: ['CONTINUOUS THICK LINE',
            'CONTINUOUS THIN LINE',
            'CHAIN THIN LINE',
            'DASHED LINE'],
        correctAnswer: 2,
    },
    {
        id:'56',
        question: 'THE NUMBERS OF PRINCIPAL VIEWS ARE',
        options: ['TWO',
            'THREE',
            'FOUR',
            'SIX'],
        correctAnswer: 3,
    },
    {
        id:'57',
        question: 'FOR ORTHOGRAPHIC PROJECTION, THE ENGINEERING CUSTOM IN THE UNITED STATE DICTATES THE USE OF',
        options: ['FIRST-ANGLE PROJECTION',
            'SECOND-ANGLE PROJECTION',
            'THIRD-ANGLE PROJECTION',
            'FOURTH-ANGLE PROJECTION'],
        correctAnswer: 2,
    },
    {
        id:'58',
        question: 'THE SEQUENCE FOR THE DIRECTION OF VIEWS (OR LINE OF SIGHT) FOR ANY ORTHOGRAPHIC PROJECTION AS UTILIZED IN THE UNITED STATES IS:',
        options: ['EYE OF OBSERVER>PROJECTION PLANE>OBJECT',
            'EYE OF OBSERVER>OBJECT>PROJECTION PLANE',
            'PROJECTION PLANE>OBJECT>EYE OF OBSERVER',
            'PROJECTION PLANE>EYE OF OBSERVER>OBJECT'],
        correctAnswer: 0,
    },
    {
        id:'59',
        question: 'A CIVIL ENGINEER WORKING ON A BRIDGE DESIGN WOULD PROBABLY RELY ON HIS _____ SCALE FOR CHECKING PRINTED DRAWINGS.',
        options: ['ENGINEERS',
            'METRIC',
            'ARCHITECTS',
            'NONE OF THESE'],
        correctAnswer: 0,
    },
    {
        id:'60',
        question: 'IN AN OBLIQUE SKETCH OF A CUBE:',
        options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
            'BOTH RECEDING AXES ARE AT 30 DEGREES TO THE HORIZONTAL',
            'ALL FACES ARE EQUALLY DISTORTED',
            'THE DEPTH DISTANCES MUST BE REDUCED'],
        correctAnswer: 0,
    },
    {
        id:'61',
        question: 'PERSPECTIVE DRAWING IS THE REPRESENTATION OF AN OBJECT ON A PLANE SURFACE IS CALLED___________',
        options: ['GROUND PLANE',
            'PICTURE PLANE',
            'HORIZONTAL PLANE',
            'CENTRAL PLANE'],
        correctAnswer: 1,
    },
    {
        id:'62',
        question: 'WHICH PLANE IS PERPENDICULAR TO BOTH THE PICTURE PLANE AND THE GROUND PLANE?',
        options: ['HORIZONTAL PLANE',
            'AUXILLARY GROUND PLANE',
            'CENTRAL PLANE',
            ' NONE OF THESE'],
        correctAnswer: 2,
    },
    {
        id:'63',
        question: 'THE POINT IN WHICH THE PERPENDICULAR AXIS PIERCES THE PICTURE PLANE IS CALLED __________',
        options: ['VANISH POINT',
            'CENTER OF VISION',
            'CENTER OF CORE',
            'CENTER OF OBJECT'],
        correctAnswer: 1,
    },
    {
        id:'64',
        question: 'AN AXONOMETRIC DRAWING WHICH HAS TWO AXES DIVIDED BY EQUAL ANGLES IS:',
        options: ['DIMETRIC',
            'TRIMETRIC',
            'ORTHOGRAPHIC',
            'ISOMETRIC'],
        correctAnswer: 0,
    },
    {
        id:'65',
        question: 'IN THIS TYPE OF PROJECTION, EACH OF THE AXES HAS DIFFERENT RATIOS OF FORESHORTENING:',
        options: ['ISOMETRIC',
            'DIMETRIC',
            'TRIMETRIC',
            'PARALLEL'],
        correctAnswer: 2,
    },
    {
        id:'66',
        question: 'IN ISOMETRIC SKETCH OF A CUBE:',
        options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
            'THE RECEDING AXES ARE AT 45 DEGREES TO THE HORIZONTAL',
            'ALL FACES ARE EQUALLY DISTORTED',
            'ONLY THE DEPTH DISTANCES MUST BE REDUCED'],
        correctAnswer: 2,
    },
    {
        id:'67',
        question: 'IN ISOMETRIC DRAWINGS:',
        options: ['TWO AXES ARE PERPENDICULAR',
            'TRUE MEASUREMENT CAN BE MADE ONLY ALONG OR PARALLEL TO THE ISOMETRIC AXES',
            'ALL FACES ARE UNEQUALLY DISTORTED',
            'NONE OF THESE'],
        correctAnswer: 1,
    },
    {
        id:'68',
        question: 'IN AN OBLIQUE SKETCH OF A CUBE:',
        options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
            'BOTH RECEDING AXES ARE AT 30 DEGREES TO THE HORIZONTAL',
            'ALL FACES ARE EQUALLY DISTORTED',
            'THE DEPTH DISTANCES MUST BE REDUCED'],
        correctAnswer: 0,
    },
    {
        id:'69',
        question: 'WHAT IS THE MAJOR DIFFERENCE(S) BETWEEN PERSPECTIVE AND PARALLEL PROJECTION?',
        options: ['PARALLEL PROJECTION CAN ONLY BE USED WITH OBJECTS CONTAING PARALLEL EDGES. PERSPECTIVE PROJECTION CAN ONLY BE USED FOR CREATING OBLIQUE AND NOT ISOMETRIC PICTORIALS',
            'PERSPECTIVE PROJECTION GIVES A MORE REALISTIC REPRESENTATION OF AN OBJECT. PARALLEL PROJECTION IS EQUIVQLENT TO A PERSPECTIVE PROJECTION WHERE THE VIEWER IS STANDING INFINITELY FAR AWAY.',
            'BOTH 1 AND 2',
            'NONE OF THESE'],
        correctAnswer: 1,
    },
    {
        id:'70',
        question: 'IN AN OBLIQUE DRAWING, ALL OF THE FOLLOWING ANGLES ARE COMMONLY USED FOR DRAWING THE DEPTH AXIS, EXCEPT:',
        options: ['30 DEGREE',
            '45 DEGREE',
            '60 DEGREE',
            '90 DEGREE'],
        correctAnswer: 3,
    },
    {
        id:'71',
        question: 'THIS TYPE OF AXONOMETRIC DRAWING HAS EQUAL FORESHORTENING ALONG TWO AXIS DIRECTIONS AND A DIFFERENT AMOUNT ON THE THIRD AXIS:',
        options: ['DIMETRIC',
            'TRIMETRIC',
            'MULTIVIEW',
            'ISOMETRIC'],
        correctAnswer: 0,
    },
    {
        id:'72',
        question: 'THIS TYPE OF SURFACE IS TIPPED TO ALL PRINCIPAL PLANES OF PROJECTION AND DOES NOT APPEAR TRUE SIZE IN ANY STANDARD VIEW:',
        options: ['FORESHORTENED',
            'PARALLEL',
            'ORTHOGRAPHIC',
            'OBLIQUE'],
        correctAnswer: 3,
    },
    {
        id:'73',
        question: 'THE TOP, FRONT AND BOTTOM VIEWS ALIGN IN THIS MANNER:',
        options: ['HORIZONTALLY',
            'VERTICALLY',
            'ACCORDING TO THE PLANAR VIEWS',
            'PARALLEL TO THE FRONTAL PLANE'],
        correctAnswer: 1,
    },
    {
        id:'74',
        question: 'PLAIN SCALE REPRESENTS _______________UNITS',
        options: ['EITHER 1 OR 2',
            'NEITHER 1 OR 2',
            '1',
            '2'],
        correctAnswer: 0,
    },
    {
        id:'75',
        question: 'THIS LINE PATTERN IS COMPOSED OF THREE DASHES, ONE LONG DASH ON EACH END WITH A SHORT IN THE MIDDLE:',
        options: ['OBJECT',
            'HIDDEN',
            'CENTER',
            'PHANTOM'],
        correctAnswer: 2,
    },
    {
        id:'76',
        question: 'THIS TYPE OF SURFACE IS TIPPED TO ALL PRINCIPAL PLANES OF PROJECTION AND DOES NOT APPEAR TRUE SIZE IN ANY STANDARD VIEW:',
        options: ['FORESHORTENED',
            'PARALLEL',
            'ORTHOGRAPHIC',
            'OBLIQUE'],
        correctAnswer: 3,
    },
    {
        id:'77',
        question: 'THESE DRAWINGS ARE GIVEN TO CONTRACTORS TO PERFORM WORK OR MANUFACTURE INDIVIDUAL PARTS:',
        options: ['ASSEMBLY DETAILS',
            '3D DRAWINGS',
            'WORKING DRAWINGS',
            '. SKELETON ASSEMBLIES'],
        correctAnswer: 2,
    },
    {
        id:'78',
        question: 'FULL FORM OF ISA:',
        options: ['INDIAN STANDARD ANGULAR',
            'INDIAN STANDARD ANALOG',
            'INDIAN STANDARD ANGUALR SECTION',
            'INDIAN STANDARD ANGLE SECTION'],
        correctAnswer: 3,
    },
    {
        id:'79',
        question: 'THIS IS THE INTERSECTION OF THE GROUND PLANE WITH THE PICTURE PLANE:',
        options: ['VANISHING POINT',
            'GROUND LINE',
            'STATION POINT',
            'HORIZON'],
        correctAnswer: 1,
    },
    {
        id:'80',
        question: 'IN PERSPECTIVE DRAWING THIS IS PLACED BETWEEN THE OBSERVER AND THE OBJECT:',
        options: ['VANISHING POINT/HORIZON',
            'STATION POINT',
            'GROUND LINE',
            'PLANE OF PROJECTION / PICTURE PLANE'],
        correctAnswer: 3,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },
    {
        id:'78',
        question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
        options: ['SINGLE VIEW PROJECTION',
            'TWO VIEW PROJECTION',
            'MULTI VIEW PROJECTION',
            'ALL OF THE ABOVE'],
        correctAnswer: 1,
    },

    

];

export default questions;