const questions = [
  {
      
      question: 'WHAT IS THE FULL FORM OF HYSD BAR?',
      options: ['HIGH YIELD STRENGTH DEFORMATION BAR',
          'HIGHEST YIELD STRENGTH DEFORMED BAR',
          'HIGHER YIELD STREE DEFORMATION BAR',
          'NONE OF THESE'],
      correctAnswer: 0,
  },
  {
      
      question: 'DEVELOPMENT OF THE PRISMS WILL BE',
      options: ['RECTANGLE',
          'N0. OF SQUARES',
          'N0. OF RECTANGLES',
          'SQUARES'],
      correctAnswer: 2,
  },
  {
      id:'3',
      question: 'FULL FORM OF BIS',
      options: ['BEST INDIAN STANDARD',
          'BOARD OF INDIAN STANDARD',
          'BUREAUE OF INDIAN STANDARD',
          'NONE OF THESE'],
      correctAnswer: 2,
  },
  {
      id:'4',
      question: 'THE SIZE OF THE DRAWING DRAWN TO SCALE 2:1 WILL BE ____________ THE ACTUAL SIZE.',
      options: ['SAME AS',
          'TWICE OF',
          'HALF OF',
          'NONE OF A, B, AND C'],
      correctAnswer: 1,
  },
  
  {
      id:'5',
      question: 'IN THE ORTHOGRAPHIC PROJECTIONS, F.V. IS PROJECTED ON',
      options: ['H.P',
          'V.P',
          'XY',
          'GL'],
      correctAnswer: 1,
  },
  {
      id:'6',
      question: 'WHEN THE DRAWING ARE DRAWN LARGER THAN THE ACTUAL SIZE OF OBJECT THEN SCALE IS KNOWN AS',
      options: ['ENLARGED SCALE',
          'REDUCED SCALE',
          'FULL SCALE',
          'STANDARD SCALE'],
      correctAnswer: 0,
  },
  {
      id:'7',
      question: 'A SPHERE CAN BE DESCRIBED IN HOW MANY VIEWS?',
      options: ['4',
          '3',
          '2',
          '1'],
      correctAnswer: 3,
  },
  {
      id:'8',
      question: 'IF POINT "C" IS BELOW HP AND BEHIND VP THEN IN WHICH QUADRANT POINT "C" LIES?',
      options: ['FIRST',
          'SECOND',
          'THIRD',
          'FOURTH'],
      correctAnswer: 2,
  },
  {
      id:'9',
      question: 'WHEN A POINT IS BELOW HP & IN FRONT OF VP IT IS IN',
      options: ['FIRST QUADRANT',
          'SECOND QUADRANT',
          'THIRD QUADRANT',
          'FOURTH QUADRANT'],
      correctAnswer: 3,
  },
  {
      id:'10',
      question: 'IN ISOMETRIC VIEW LENGTH, WIDTH, AND HEIGHT ARE INCLINED AT',
      options: ['30',
                '60',
                '90',
                '120'],
      correctAnswer: 3,
  },
  {
      id:'11',
      question: 'SECOND ANGLE PROJECTION IS NOT USED BECAUSE',
      options: ['PLAN IS ABOVE XY',
          'BOTH VIEWS OVERLAP EACH OTHER',
          'ELEVATION IS ABOVE XY',
          'VIEWS ARE SMALL IN SIZE'],
      correctAnswer: 1,
  },
  {
      id:'12',
      question: 'LENGTH (L) OF LINE IN ISOMETRIC VIEW WILL BE EQUAL TO',
      options: ['0.707 L',
          '0.815 L',
          'TRUE LENGTH L',
          '0.866 L'],
      correctAnswer: 2,
  },
  {
      id:'13',
      question: 'DASHED LINE IS USED TO DRAW',
      options: ['OUTER EDGES',
          'PROJECTIONS',
          'CENTER & CENTER AXIS',
          'HIDDEN FACES'],
      correctAnswer: 3,
  },
  {
      id:'14',
      question: 'A SQUARE PLANE IS INCLINED TO VP & PERPENDICULAR TO HP ITS ELEVATION APPEARS AS',
      options: ['RHOMBUS',
          'SQUARE',
          'STRAIGHT LINE',
          'RECTANGLE'],
      correctAnswer: 2,
  },
  {
      id:'15',
      question: 'IF LINE IS INCLINED TO VERTICAL PLANE AND PARALLEL TO HORIZONTAL PLANE, THEN WHICH ONE OF THE FOLLOWING IS ALWAYS CORRECT?',
      options: ['TRUE LENGTH = PLAN LENGTH',
          'TRUE LENGTH = ELEVATION LENGTH',
          'TRUE LENGTH ≠ PLAN LENGTH',
          'NONE OF THESE'],
      correctAnswer: 0,
  },
  {
      id:'16',
      question: 'IN FIRST ANGLE PROJECTION METHOD THE LEFT HAND SIDE VIEW IS PLACED ON',
      options: ['ABOVE ELEVATION',
          'BELOW ELEVATION',
          'RIGHT SIDE OF F. V. (ELEVATION)',
          'AXONOMETRIC'],
      correctAnswer: 2,
  },
  {
      id:'17',
      question: 'WHICH ONE OF THE FOLLOWING IS NOT A REDUCING SCALE?',
      options: ['1:1',
          '1:200',
          '5:320',
          '5:6'],
      correctAnswer: 0,
  },
  {
      id:'18',
      question: 'WHAT IS THE FULL FORM OF HYSD BAR?',
      options: ['IN FRONT OF V.P. AND ABOVE H.P',
          'BEHIND V.P. AND BELOW H.P',
          'IN FRONT OF V.P. AND BELOW H.P',
          'BEHIND V.P. AND ABOVE H.P'],
      correctAnswer: 3,
  },
  {
      id:'19',
      question: 'WHEN THE DRAWING ARE DRAWN SMALLER THAN THE ACTUAL SIZE OF OBJECT THEN SCALE IS KNOWN AS',
      options: ['REDUCED SCALE',
          'ENLARGED SCALE',
          'FULL SCALE',
          'NONE OF THESE'],
      correctAnswer: 0,
  },
  {
      id:'20',
      question: 'IN A THIRD ANGLE PROJECTION METHOD, RIGHT HAND SIDE VIEW OF AN OBJECT IS DRAWN ___________ FRONT VIEW',
      options: ['LEFT SIDE OF',
          'RIGHT SIDE OF',
          'REAR SIDE OF',
          'NONE OF THE ABOVE'],
      correctAnswer: 1,
  },
  {
      id:'21',
      question: 'IF THE 10 M LENGTH IS REPRESENTED AS 1 CM ON THE MAP THEN REPRESENTATIVE FRACTION IS',
      options: ['1/100',
          '1/10',
          '1/1000',
          'NONE OF THE ABOVE'],
      correctAnswer: 2,
  },
  {
      id:'22',
      question: 'FOURTH ANGLE PROJECTION IS NOT USED BECAUSE',
      options: [' FRONT VIEW IS ABOVE REFERENCE LINE AND TOP VIEW IS BELOW REFERENCE LINE',
          'TOP VIEW IS ABOVE REFERENCE LINE AND FRONT VIEW IS BELOW REFERENCE LINE',
          'FRONT VIEW AND TOP VIEW BOTH OVERLAP ON EACH OTHER AND BELOW REFERENCE LINE',
          'FRONT VIEW AND TOP VIEW BOTH OVERLAP ON EACH OTHER AND ABOVE THE REFERENCE LINE'],
      correctAnswer: 2,
  },
  {
      id:'23',
      question: 'FOR THE THIRD ANGLE PROJECTION METHOD, WHICH OF THE FOLLOWING IS CORRECT?',
      options: ['OBSERVER  OBJECT  PLANE',
          'OBSERVER  PLANE  OBJECT',
          '(A) AND (B) BOTH',
          'NONE OF THE ABOVE'],
      correctAnswer: 1,
  },
  {
      id:'24',
      question: 'NAME THE SOLID FORMED BY FOUR EQUILATERAL TRIANGLES',
      options: ['SQUARE PYRAMID',
          'TRIANGULAR PYRAMID',
          'TETRAHEDRON',
          'SQUARE PRISM'],
      correctAnswer: 2,
  },
  {
      id:'25',
      question: 'A CYLINDER STANDING ON THE HP IS CUT BY A VERTICAL PLANE PARALLEL TO THE AXIS AND AWAY FROM IT. THE SHAPE OF THE SECTION WILL BE',
      options: ['RECTANGLE',
          'ELLIPSE',
          'PARABOLA',
          'HYPERBOLA'],
      correctAnswer: 0,
  },
  {
      id:'26',
      question: '1FT=________CM',
      options: ['30.48',
          '0.3048',
          '3.28',
          '35.31'],
      correctAnswer: 0,
  },
  {
      id:'27',
      question: '1 KM=_____CM',
      options: ['10000',
          '100000',
          '100',
          '12000'],
      correctAnswer: 1,
  },
  {
      id:'28',
      question: 'THE RATIO OF THE LENGTH OF THE DRAWING OF THE OBJECT TO THE ACTUAL LENGTH OF THE OBJECT IS CALLED _________________',
      options: ['RESULTING FRACTION',
          'REPRESENTATIVE FRACTION',
          'REPRESENTATIVE FACTOR',
          'NONE OF THESE'],
      correctAnswer: 1,
  },
  {
      id:'29',
      question: 'FOR ANGULAR MEASUREMENT WE USE WHICH TYPE OF SCALE?',
      options: ['VERNIER SCALE',
          'ISOMETRIC SCALE',
          'SCALE OF CHORD',
          'NONE OF THESE'],
      correctAnswer: 2,
  },
  {
      id:'30',
      question: 'THE TWO WAYS OF DRAWINGS ORTHOGRAPHIC PROJECTION ARE',
      options: ['FIRST ANGLE, SECOND ANGLE',
          'FIRST ANGLE, THIRD ANGLE',
          'FIRST ANGLE, FOURTH ANGLE',
          'FOURTH ANGLE, SECOND ANGLE'],
      correctAnswer: 1,
  },
  {
      id:'31',
      question: 'THE SEQUENCE FOR THE DIRECTION OF VIEWS (OR LINE OF SIGHT) FOR ANY ORTHOGRAPHIC PROJECTION AS UTILIZED IN THE UNITED STATES IS',
      options: ['EYE OF OBSERVER>PROJECTION PLANE>OBJECT',
          'EYE OF OBSERVER>OBJECT>PROJECTION PLANE',
          'PROJECTION PLANE>OBJECT>EYE OF OBSERVER',
          'PROJECTION PLANE>EYE OF OBSERVER>OBJECT'],
      correctAnswer: 0,
  },
  {
      id:'32',
      question: 'IN WORKING DRAWINGS, THESE SHOW ALL NECESSARY INFORMATION NOT GIVEN DIRECTLY ON THE DRAWING WITH ITS DIMENSIONS AND NOTES',
      options: ['DOCUMENT STRIPS',
          'PORTABLE DOCUMENTS',
          'FORMATTING FORMS',
          'TITLE AND RECORD STRIPS'],
      correctAnswer: 3,
  },
  {
      id:'33',
      question: 'SPHERE IS THE REVOLUTION OF ________________.',
      options: ['RECTANGLE',
          'CIRCLE',
          'SEMI CIRCLE',
          'TRIANGLE'],
      correctAnswer: 2,
  },
  {
      id:'34',
      question: 'PERSPECTIVE PROJECTION IS ESSENTIAL TO HAVE FULL KNOWLEDGE OF',
      options: ['FIRST ANGLE METHOD',
          'THIRD ANGLE METHOD',
          'FOURTH ANGLE METHOD',
          'NONE OF THESE'],
      correctAnswer: 1,
  },
  {
      id:'35',
      question: 'WHEN THE PROJECTORS ARE PARALLEL TO EACH OTHER AND ALSO PERPENDICULAR TO THE PLANE, THE PROJECTION IS CALLED?',
      options: ['ISOMETRIC PROJECTION',
          'ORTHOGRAPHIC PROJECTION',
          'PERSPECTIVE PROJECTION',
          'AXONOMETRIC PROJECTION'],
      correctAnswer: 1,
  },
  {
      id:'36',
      question: 'IN WHICH PROJECTION THE PLANES OF PROJECTION ARE ASSUMED TO BE TRANSPARENT',
      options: ['1ST ANGLE PROJECTION',
          '3RD ANGLE PROJECTION',
          '4TH ANGLE PROJECTION',
          '2ND ANGLE PROJECTION'],
      correctAnswer: 1,
  },
  {
      id:'37',
      question: 'IN WHICH PROJECTION THE OBJECT LIES BETWEEN THE OBSERVER AND THE PLANE OF PROJECTION',
      options: ['1ST ANGLE PROJECTION',
          '3RD ANGLE PROJECTION',
          '4TH ANGLE PROJECTION',
          '2ND ANGLE PROJECTION'],
      correctAnswer: 0,
  },
  {
      id:'38',
      question: 'IN 1ST ANGLE PROJECTION THE OBJECT IS SITUATED IN WHICH QUADRANT?',
      options: ['1ST QUADRANT',
          '2ND QUADRANT',
          '3RD QUADRANT',
          '4TH QUADRANT'],
      correctAnswer: 0,
  },
  {
      id:'39',
      question: 'THE PLANE OF PROJECTION LIES BETWEEN THE OBSERVER AND THE OBJECT',
      options: ['1ST ANGLE PROJECTION',
          '3RD ANGLE PROJECTION',
          '4TH ANGLE PROJECTION',
          '2ND ANGLE PROJECTION'],
      correctAnswer: 1,
  },
  {
      id:'40',
      question: 'THE PLANE OF PROJECTION LIES BETWEEN THE OBSERVER AND THE OBJECT',
      options: ['1ST ANGLE PROJECTION',
          '3RD ANGLE PROJECTION',
          '4TH ANGLE PROJECTION',
          '2ND ANGLE PROJECTION'],
      correctAnswer: 1,
  },
  {
      id:'41',
      question: 'IN AN OBLIQUE PROJECTION ALSO, THERE ARE THREE AXES - A VERTICAL, A HORIZONTAL AND A THIRD,INCLINED AT AN ANGLE OF WITH THE HORIZONTAL.',
      options: ['30° OR 25°',
          '30° OR 45°',
          '35° OR 40°',
          '60° OR 35°'],
      correctAnswer: 1,
  },
  {
      id:'42',
      question: 'WHICH OF THE FOLLOWING IS NOT A PICTORIAL DRAWING?',
      options: ['ISOMETRIC',
          'MULTIVIEW',
          'PERSPECTIVE',
          'AXONOMETRIC'],
      correctAnswer: 1,
  },
  {
      id:'43',
      question: 'WHICH OF THE FOLLOWING PROJECTION METHODS DOES NOT USE PROJECTORS PERPENDICULAR TO THE PLANE OF PROJECTION?',
      options: ['ISOMETRIC',
          'ORTHOGRAPHIC',
          'OBLIQUE',
          'AXONOMETRIC'],
      correctAnswer: 2,
  },
  {
      id:'44',
      question: 'A CIRCLE WILL APPEAR ON AN ISOMETRIC DRAWING AS A (N) __________.',
      options: ['ELLIPSE',
          'CYCLOID',
          'CIRCLE',
          'PARABOLA'],
      correctAnswer: 0,
  },
  {
      id:'45',
      question: 'IN AN OBLIQUE DRAWING, THE PROJECTION RAYS ARE DRAWN____________TO EACH OTHER AND________TO THE PLANE OF PROJECTION.',
      options: ['INCLINED....INCLINED',
          'INCLINED.......PARALLEL',
          'PARALLEL.......INCLINED',
          'PARALLEL.....PARALLEL'],
      correctAnswer: 2,
  },
  {
      id:'46',
      question: 'WHEN THE DRAWING IS DRAWN OF THE SAME SIZE AS THAT OF THE OBJECT, THE SCALE USED IS _______',
      options: ['DIAGONAL SCALE',
          'FULL-SIZE SCALE',
          'VERNIER SCALE',
          'PLAIN SCALE'],
      correctAnswer: 1,
  },
  {
      id:'47',
      question: 'WHICH TYPE OF LINE IS PARTICULAR TO SECTION DRAWINGS?',
      options: ['BREAK LINES',
          'PHANTOM LINES',
          'EXTENSION LINES',
          'CUTTING PLANE LINES'],
      correctAnswer: 3,
  },
  {
      id:'48',
      question: 'WHICH TYPE OF LINE IS PART OF A DIMENSION?',
      options: ['BREAK LINES',
      'PHANTOM LINES',
      'EXTENSION LINES',
      'CUTTING PLANE LINES'],
  correctAnswer: 2,
  },
  {
      id:'49',
      question: 'IN AN AXONOMETRIC DRAWING, THE PROJECTION RAYS ARE DRAWN______TO EACH OTHER AND ______ TO THE PLANE OF PROJECTION.',
      options: ['PARRLLEL.....OBLIQUE',
          'OBLIQUE.....PARALLEL',
          'PARALLEL....PERPENDICULAR',
          'PARALLEL.....PARALLEL'],
      correctAnswer: 2,
  },
  {
      id:'50',
      question: 'IN WHICH PROJECTION METHOD THE PLANE OF PROJECTION IS ASSUMED NON-TRANSPARENT?',
      options: ['FIRST ANGLE PROJECTION METHOD',
          'SECOND ANGLE PROJECTION METHOD',
          'THIRD ANGLE PROJECTION METHOD',
          'BOTH FIRST ANGLE AND THIRD ANGLE PROJECTION METHOD'],
      correctAnswer: 3,
  },
  {
      id:'51',
      question: 'IMAGINE AN "L" SHAPED FACE EXTRUDED INTO THREE DIMENSIONS. HOW MANY FACES DOES IT CONTAIN?',
      options: ['SEVEN',
          'EIGHT',
          'TEN',
          'SIX'],
      correctAnswer: 1,
  },
  {
      id:'52',
      question: 'THE POINT, FROM WHICH THE OBSERVER IS ASSUMED TO VIEW THE OBJECT, IS CALLED',
      options: ['CENTER OF PROJECTION',
          'POINT OF PROJECTION',
          'POINT OF OBSERVER',
          'VIEW POINT'],
      correctAnswer: 0,
  },
  {
      id:'53',
      question: 'IN THE TERM ORTHO-GRAPHIC, "ORTHOS" MEANS',
      options: ['DRAWING',
          'STRAIGHT',
          'PROJECTION',
          'VIEW'],
      correctAnswer: 1,
  },
  {
      id:'54',
      question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
      options: ['SINGLE VIEW PROJECTION',
          'TWO VIEW PROJECTION',
          'MULTI VIEW PROJECTION',
          'ALL OF THE ABOVE'],
      correctAnswer: 2,
  },
  {
      id:'55',
      question: 'CENTER LINE IS',
      options: ['CONTINUOUS THICK LINE',
          'CONTINUOUS THIN LINE',
          'CHAIN THIN LINE',
          'DASHED LINE'],
      correctAnswer: 2,
  },
  {
      id:'56',
      question: 'THE NUMBERS OF PRINCIPAL VIEWS ARE',
      options: ['TWO',
          'THREE',
          'FOUR',
          'SIX'],
      correctAnswer: 3,
  },
  {
      id:'57',
      question: 'FOR ORTHOGRAPHIC PROJECTION, THE ENGINEERING CUSTOM IN THE UNITED STATE DICTATES THE USE OF',
      options: ['FIRST-ANGLE PROJECTION',
          'SECOND-ANGLE PROJECTION',
          'THIRD-ANGLE PROJECTION',
          'FOURTH-ANGLE PROJECTION'],
      correctAnswer: 2,
  },
  {
      id:'58',
      question: 'THE SEQUENCE FOR THE DIRECTION OF VIEWS (OR LINE OF SIGHT) FOR ANY ORTHOGRAPHIC PROJECTION AS UTILIZED IN THE UNITED STATES IS:',
      options: ['EYE OF OBSERVER>PROJECTION PLANE>OBJECT',
          'EYE OF OBSERVER>OBJECT>PROJECTION PLANE',
          'PROJECTION PLANE>OBJECT>EYE OF OBSERVER',
          'PROJECTION PLANE>EYE OF OBSERVER>OBJECT'],
      correctAnswer: 0,
  },
  {
      id:'59',
      question: 'A CIVIL ENGINEER WORKING ON A BRIDGE DESIGN WOULD PROBABLY RELY ON HIS _____ SCALE FOR CHECKING PRINTED DRAWINGS.',
      options: ['ENGINEERS',
          'METRIC',
          'ARCHITECTS',
          'NONE OF THESE'],
      correctAnswer: 0,
  },
  {
      id:'60',
      question: 'IN AN OBLIQUE SKETCH OF A CUBE:',
      options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
          'BOTH RECEDING AXES ARE AT 30 DEGREES TO THE HORIZONTAL',
          'ALL FACES ARE EQUALLY DISTORTED',
          'THE DEPTH DISTANCES MUST BE REDUCED'],
      correctAnswer: 0,
  },
  {
      id:'61',
      question: 'PERSPECTIVE DRAWING IS THE REPRESENTATION OF AN OBJECT ON A PLANE SURFACE IS CALLED___________',
      options: ['GROUND PLANE',
          'PICTURE PLANE',
          'HORIZONTAL PLANE',
          'CENTRAL PLANE'],
      correctAnswer: 1,
  },
  {
      id:'62',
      question: 'WHICH PLANE IS PERPENDICULAR TO BOTH THE PICTURE PLANE AND THE GROUND PLANE?',
      options: ['HORIZONTAL PLANE',
          'AUXILLARY GROUND PLANE',
          'CENTRAL PLANE',
          ' NONE OF THESE'],
      correctAnswer: 2,
  },
  {
      id:'63',
      question: 'THE POINT IN WHICH THE PERPENDICULAR AXIS PIERCES THE PICTURE PLANE IS CALLED __________',
      options: ['VANISH POINT',
          'CENTER OF VISION',
          'CENTER OF CORE',
          'CENTER OF OBJECT'],
      correctAnswer: 1,
  },
  {
      id:'64',
      question: 'AN AXONOMETRIC DRAWING WHICH HAS TWO AXES DIVIDED BY EQUAL ANGLES IS:',
      options: ['DIMETRIC',
          'TRIMETRIC',
          'ORTHOGRAPHIC',
          'ISOMETRIC'],
      correctAnswer: 0,
  },
  {
      id:'65',
      question: 'IN THIS TYPE OF PROJECTION, EACH OF THE AXES HAS DIFFERENT RATIOS OF FORESHORTENING:',
      options: ['ISOMETRIC',
          'DIMETRIC',
          'TRIMETRIC',
          'PARALLEL'],
      correctAnswer: 2,
  },
  {
      id:'66',
      question: 'IN ISOMETRIC SKETCH OF A CUBE:',
      options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
          'THE RECEDING AXES ARE AT 45 DEGREES TO THE HORIZONTAL',
          'ALL FACES ARE EQUALLY DISTORTED',
          'ONLY THE DEPTH DISTANCES MUST BE REDUCED'],
      correctAnswer: 2,
  },
  {
      id:'67',
      question: 'IN ISOMETRIC DRAWINGS:',
      options: ['TWO AXES ARE PERPENDICULAR',
          'TRUE MEASUREMENT CAN BE MADE ONLY ALONG OR PARALLEL TO THE ISOMETRIC AXES',
          'ALL FACES ARE UNEQUALLY DISTORTED',
          'NONE OF THESE'],
      correctAnswer: 1,
  },
  {
      id:'68',
      question: 'IN AN OBLIQUE SKETCH OF A CUBE:',
      options: ['THE FRONTAL FACE APPEARS IN ITS TRUE SHAPE',
          'BOTH RECEDING AXES ARE AT 30 DEGREES TO THE HORIZONTAL',
          'ALL FACES ARE EQUALLY DISTORTED',
          'THE DEPTH DISTANCES MUST BE REDUCED'],
      correctAnswer: 0,
  },
  {
      id:'69',
      question: 'WHAT IS THE MAJOR DIFFERENCE(S) BETWEEN PERSPECTIVE AND PARALLEL PROJECTION?',
      options: ['PARALLEL PROJECTION CAN ONLY BE USED WITH OBJECTS CONTAING PARALLEL EDGES. PERSPECTIVE PROJECTION CAN ONLY BE USED FOR CREATING OBLIQUE AND NOT ISOMETRIC PICTORIALS',
          'PERSPECTIVE PROJECTION GIVES A MORE REALISTIC REPRESENTATION OF AN OBJECT. PARALLEL PROJECTION IS EQUIVQLENT TO A PERSPECTIVE PROJECTION WHERE THE VIEWER IS STANDING INFINITELY FAR AWAY.',
          'BOTH 1 AND 2',
          'NONE OF THESE'],
      correctAnswer: 1,
  },
  {
      id:'70',
      question: 'IN AN OBLIQUE DRAWING, ALL OF THE FOLLOWING ANGLES ARE COMMONLY USED FOR DRAWING THE DEPTH AXIS, EXCEPT:',
      options: ['30 DEGREE',
          '45 DEGREE',
          '60 DEGREE',
          '90 DEGREE'],
      correctAnswer: 3,
  },
  {
      id:'71',
      question: 'THIS TYPE OF AXONOMETRIC DRAWING HAS EQUAL FORESHORTENING ALONG TWO AXIS DIRECTIONS AND A DIFFERENT AMOUNT ON THE THIRD AXIS:',
      options: ['DIMETRIC',
          'TRIMETRIC',
          'MULTIVIEW',
          'ISOMETRIC'],
      correctAnswer: 0,
  },
  {
      id:'72',
      question: 'THIS TYPE OF SURFACE IS TIPPED TO ALL PRINCIPAL PLANES OF PROJECTION AND DOES NOT APPEAR TRUE SIZE IN ANY STANDARD VIEW:',
      options: ['FORESHORTENED',
          'PARALLEL',
          'ORTHOGRAPHIC',
          'OBLIQUE'],
      correctAnswer: 3,
  },
  {
      id:'73',
      question: 'THE TOP, FRONT AND BOTTOM VIEWS ALIGN IN THIS MANNER:',
      options: ['HORIZONTALLY',
          'VERTICALLY',
          'ACCORDING TO THE PLANAR VIEWS',
          'PARALLEL TO THE FRONTAL PLANE'],
      correctAnswer: 1,
  },
  {
      id:'74',
      question: 'PLAIN SCALE REPRESENTS _______________UNITS',
      options: ['EITHER 1 OR 2',
          'NEITHER 1 OR 2',
          '1',
          '2'],
      correctAnswer: 0,
  },
  {
      id:'75',
      question: 'THIS LINE PATTERN IS COMPOSED OF THREE DASHES, ONE LONG DASH ON EACH END WITH A SHORT IN THE MIDDLE:',
      options: ['OBJECT',
          'HIDDEN',
          'CENTER',
          'PHANTOM'],
      correctAnswer: 2,
  },
  {
      id:'76',
      question: 'THIS TYPE OF SURFACE IS TIPPED TO ALL PRINCIPAL PLANES OF PROJECTION AND DOES NOT APPEAR TRUE SIZE IN ANY STANDARD VIEW:',
      options: ['FORESHORTENED',
          'PARALLEL',
          'ORTHOGRAPHIC',
          'OBLIQUE'],
      correctAnswer: 3,
  },
  {
      id:'77',
      question: 'THESE DRAWINGS ARE GIVEN TO CONTRACTORS TO PERFORM WORK OR MANUFACTURE INDIVIDUAL PARTS:',
      options: ['ASSEMBLY DETAILS',
          '3D DRAWINGS',
          'WORKING DRAWINGS',
          '. SKELETON ASSEMBLIES'],
      correctAnswer: 2,
  },
  {
      id:'78',
      question: 'FULL FORM OF ISA:',
      options: ['INDIAN STANDARD ANGULAR',
          'INDIAN STANDARD ANALOG',
          'INDIAN STANDARD ANGUALR SECTION',
          'INDIAN STANDARD ANGLE SECTION'],
      correctAnswer: 3,
  },
  {
      id:'79',
      question: 'THIS IS THE INTERSECTION OF THE GROUND PLANE WITH THE PICTURE PLANE:',
      options: ['VANISHING POINT',
          'GROUND LINE',
          'STATION POINT',
          'HORIZON'],
      correctAnswer: 1,
  },
  {
      id:'80',
      question: 'IN PERSPECTIVE DRAWING THIS IS PLACED BETWEEN THE OBSERVER AND THE OBJECT:',
      options: ['VANISHING POINT/HORIZON',
          'STATION POINT',
          'GROUND LINE',
          'PLANE OF PROJECTION / PICTURE PLANE'],
      correctAnswer: 3,
  },
  {
      id:'81',
      question: 'WHEN POSITIONING THIS FEATURE OF PERSPECTIVE PROJECTION, THE CENTERLINE OF THE CONE OF VISUAL RAYS SHOULD BE DIRECTED TOWARD THE APPROXIMATE CENTER OF THE OBJECT:',
      options: ['STATION POINT',
          'VANISHING POINT',
          'HORIZON',
          'GROUND LINE'],
      correctAnswer: 0,
  },
  {
      id:'82',
      question: 'PERSPECTIVE DRAWINGS ARE CLASSIFIED ACCORDING TO THEIR NUMBER OF THESE FEATURES:',
      options: ['STATION POINTS',
          'PICTURE PLANES',
          'VANISHING POINTS',
          'GROUND LINES'],
      correctAnswer: 2,
  },
  {
      id:'83',
      question: 'ARCHITECTURAL DRAFTERS GENERALLY PREFER TO USE _________DRAWINGS TO HELP ILLUSTRATE 3-DIMENSIONAL VIEWS OF A STRUCTURE.',
      options: ['ISOMETRIC',
          'PERSPECTIVE',
          'ORTHOGRAPHIC',
          'AUXILLARY'],
      correctAnswer: 1,
  },
  {
      id:'84',
      question: 'ORTHOGRAPHIC PROJECTION IS ALSO KNOWN AS',
      options: ['SINGLE VIEW PROJECTION',
          'TWO VIEW PROJECTION',
          'MULTI VIEW PROJECTION',
          'ALL OF THE ABOVE'],
      correctAnswer: 1,
  },
  {
      id:'85',
      question: 'WHEN THE RECEDING LINES ARE TRUE LENGTH , AND THE PROJECTORS ARE AT 45 DEGREES TO THE PLANE OF PROJECTION, THE OBLIQUE DRAWING IS CALLED THIS:',
      options: ['CABINET PROJECTION',
          'CAVALIER PROJECTION',
          'AXONOMETRIC PROJECTION',
          'ISOMETRIC PROJECTION'],
      correctAnswer: 1,
  },
  {
      id:'86',
      question: 'THE FOLLOWING IS THE METHOD FOR DEVELOPMENT OF A RIGHT REGULAR PRISM.',
      options: ['PARALLEL LINE METHOD',
          'RADIAL LINE METHOD',
          'TRIANGULATION METHOD',
          'APPROXIMATE METHOD'],
      correctAnswer: 3,
  },
  {
      id:'87',
      question: 'DEVELOPMENT OF SURFACES IS USED IN THE DEVELOPMENT OF',
      options: ['PIPING',
          'AIR CONDITIONING DUCT',
          'BUCKETS',
          'ALL OF THE ABOVE'],
      correctAnswer: 3,
  },
  {
      id:'88',
      question: 'THE DEVELOPMENT OF CYLINDER IS A',
      options: ['RECTANGLE',
          'CIRCLE',
          'ELLIPSE',
          'NONE OF THESE'],
      correctAnswer: 0,
  },
  {
      id:'89',
      question: 'ZONE METHOD IS USED TO DEVELOP',
      options: ['PRISM',
          'PYRAMID',
          'CONE',
          'SPHERE'],
      correctAnswer: 3,
  },
  {
      id:'90',
      question: 'THE DEVELOPMENT OF LATERAL SURFACES OF A PENTAGONAL PYRAMID IS ______.',
      options: ['FIVE SQUARES',
          'FIVE RECTANGLES',
          'FIVE TRIANGLES',
          'NONE OF THESE'],
      correctAnswer: 2,
  },
  {
      id:'91',
      question: 'THE ISOMETRIC LENGTH IS ______PERCENT OF ACTUAL LENGTH.',
      options: ['61.5',
          ' 71.5',
          '82',
          '91.5'],
      correctAnswer: 2,
  },
  {
      id:'92',
      question: 'THE FOLLOWING IS (ARE) THE METHOD(S) OF PROJECTING THE PICTORIAL VIEWS.',
      options: ['AXONOMETRIC PROJECTION',
          'OBLIQUE PROJECTION',
          'PERSPECTIVE PROJECTION',
          'ALL OF THE ABOVE'],
      correctAnswer: 3,
  },
  {
      id:'93',
      question: 'THE ISOMETRIC AXIS ARE INCLINED AT ____ DEGREE TO EACH OTHER',
      options: ['60',
          '90',
          '120',
          '150'],
      correctAnswer: 2,
  },
  {
      id:'94',
      question: 'THE FOLLOWING ARE THE METHODS FOR DRAWING ISOMETRIC VIEWS EXCEPT',
      options: ['BOX METHOD',
          'OFFSET METHOD',
          'CENTER LINES METHOD',
          'PARALLEL LINE METHOD'],
      correctAnswer: 3,
  },
  {
      id:'95',
      question: 'A ICOSAHEDRON HAS ________FACES',
      options: ['12 EQUAL PENTAGON',
          '12 EQUAL TRIANGULAR',
          '20 EQUAL PENTAGONAL',
          '20 EQUAL TRIANGULAR'],
      correctAnswer: 3,
  },
  {
      id:'96',
      question: 'A DODECAHEDRON HAS _________ FACES.',
      options: ['24 EQUILATERAL TRIANGLE',
          '20 EQUILATERAL TRIANGLE',
          '12 EQUAL PENTAGONAL',
          '15 EQUAL PENTAGONAL'],
      correctAnswer: 2,
  },
  {
      id:'97',
      question: 'THE SECTIONAL PLANE ARE REPRESENTED BY',
      options: ['CONTINUOUS THICK LINE',
          'CONTINUOUS THIN LINE',
          'CHAIN THIN LINE',
          'CHAIN THIN LINE HAVING THICK EDGES'],
      correctAnswer: 3,
  },
  {
    id:'98',
    question: 'A LINE OF 10 METER IS SHOWN BY 2 CM ON A SCALE.ITS REPRESENTATIVE FRACTION (RF) IS',
    options: ['1/100',
        '1/50',
        '1/10',
        '1/500'],
    correctAnswer: 3,
},
{
  id:'99',
  question: '"SCALE FCATOR"(SF) IS DEFINED AS',
  options: ['LENGTH OF AN OBJECT IN THE DRAWING / ACTUAL LENGTH OF THE OBJECT',
      'LENGTH OF AN OBJECT IN THE DRAWING / ISOMETRIC LENGTH OF THE OBJECT',
      'ACTUAL LENGTH OF THE OBJECT / LENGTH OF AN OBJECT IN DRAWING',
      '. ISOMETRIC LENGTH OF THE OBJECT/ LENGTH OF AN OBJECT IN THE DRAWING'],
  correctAnswer: 0,
},
{
  id:'100',
  question: ' A POINT "P" IS BELOW HORIZONTAL PLANE (HP) AND IN FRONT OF VERTICAL PLANE (VP). THE POINT IS IN',
  options: ['FIRST QUADRANT',
      'SECOND QUADRANT',
      'THIRD QUADRANT',
      'FOURTH QUADRANT'],
  correctAnswer: 3,
},
{
  id:'101',
  question: '1MM=__________FT',
  options: ['3.28',
      '39.37',
      '0.003',
      '0.328'],
  correctAnswer: 2,
},
{
  id:'102',
  question: '1 HECTARE=___________ ACRE',
  options: ['2.47',
      '0.247',
      '0.4047',
      '1.47'],
  correctAnswer: 0,
},
{
  id:'103',
  question: '1 HECTARE=____________SQ. FT',
  options: ['10.7639104',
      '1076.39104',
      '1076391.04',
      '107639.104'],
  correctAnswer: 3,
},
{
  id:'104',
  question: 'WHERE DO THE PROJECTION LINES CONVERGE IN A PERSPECTIVE SKETCH?',
  options: ['THE VANISHING POINT',
      'THE GROUND LINE',
      'THE HORIZON LINE',
      'THE EYE POINT'],
  correctAnswer: 0,
},
{
  id:'105',
  question: 'IN AN OCTAHEDRON HOW MANY FACES IS THERE?',
  options: ['8 EQUAL TRIANGULAR FACES',
      '12 EQUAL TRIANGULAR FACES',
      '10 EQUAL TRIANGULAR FACES',
      '12 EQUAL PENTAGONAL FACES'],
  correctAnswer: 2,
},
{
  id:'106',
  question: 'WHAT TYPE OF SKETCH SHOWS THE FRONT IN TRUE SHAPE?',
  options: ['ISOMETRIC',
      'PERSPECTIVE',
      'OBLIQUE',
      'NONE OF THESE'],
  correctAnswer: 2,
},
{
  id:'107',
  question: 'THIS IS THE PLANE UPON WHICH THE TOP VIEW IS PROJECTED:',
  options: ['HORIZONTAL',
      'FRONTAL',
      'PROFILE',
      'BASE'],
  correctAnswer: 0,
},
{
  id:'108',
  question: 'THE REVOLUTION OF RIGHT ANGLE TRIANGLE ABOUT ONE OF ITS PERPENDICULAR SIDES WHICH IS FIXED, IS KNOWN AS________',
  options: ['CYLINDER',
      'CONE',
      'SPHERE',
      'NONE OF THESE'],
  correctAnswer: 1,
},
{
  id:'109',
  question: 'IF THE RECEDING LINES ARE DRAWN TO HALF SIZE SCALE SUCH OBLIQUE PROJECTION IS KNOWN AS__________',
  options: ['CABINET PROJECTION',
      'CAVALIER PROJECTION',
      'BOTH A AND B',
      'NONE OF THESE'],
  correctAnswer: 3,
},
{
  id:'110',
  question: 'THE POINT IN WHICH THE PERPENDICULAR AXIS PIERCES THE PICTURE PLANE IS CALLED________',
  options: ['CENTRAL PLANE',
      'CENTER OF VISION',
      'BOTH A AND B',
      'NONE OF THESE'],
  correctAnswer: 1,
},
{
  id:'111',
  question: '1 MILE=_____YARDS',
  options: ['1760',
      '1.609',
      '17.60',
      '1.760'],
  correctAnswer: 0,
},
{
  id:'112',
  question: '1 MILE=________KILOMETER',
  options: ['1.609',
      '160.9',
      '1760',
      '1024'],
  correctAnswer: 0,
},
{
  id:'113',
  question: '1 YARD=_______GAJ',
  options: ['0.333',
      '2.54',
      '121',
      '1'],
  correctAnswer: 3,
},
{
  id:'114',
  question: '1 HECTARE=_________DECIMAL',
  options: ['2.47',
      '247',
      '2.57',
      '100'],
  correctAnswer: 1,
},
{
  id:'115',
  question: '1 CU.M=________CU.FT',
  options: ['39.37',
      '10.76',
      '35.37',
      '35.31'],
  correctAnswer: 3,
},
{
  id:'116',
  question: '1 DECIMAL=__________SQ M',
  options: ['436',
      '40.5',
      '10.76',
      '35.31'],
  correctAnswer: 1,
},
{
  id:'117',
  question: '1 ACRE=_________SQ.FT',
  options: ['436',
      '10.76',
      '43600',
      '43600'],
  correctAnswer: 2,
},
{
  id:'118',
  question: '1 ACRE=_______HECTARE',
  options: ['40.47',
      '4.407',
      '0.4047',
      '404.7'],
  correctAnswer: 2,
},
{
  id:'119',
  question: '1 GAJ=_________INCH',
  options: ['3',
      '30',
      '36',
      '46'],
  correctAnswer: 2,
},

{
  id:'120',
  question: 'FULL FORM OF MSD',
  options: ['MEASURED SCALE DIFFERENCE',
      'MEAN SCALE DIMENSION',
      'MAIN SCALE DIVISION',
      'MULTI SCALE DIVISION'],
  correctAnswer: 2,
},

{
  id:'121',
  question: 'WHAT DO YOU MEAN BY VSD?',
  options: ['VERTICAL SCALE DIVISION',
      'VERY SMALL DIVISION',
      'VISUAL SCALED DIMENSION',
      'VERNIER SCALE DIVISION'],
  correctAnswer: 3,
},

{
  id:'122',
  question: '1-POINT PERSPECTIVE IS ALSO KNOWN AS________',
  options: ['ANGULAR PERSPECTIVE',
      'OBLIQUE PERSPECTIVE',
      'PARALLEL PERSPECTIVE',
      'ACTUAL PERSPECTIVE'],
  correctAnswer: 2,
},

{
  id:'123',
  question: '2-POINT PERSPECTIVE IS ALSO KNOWN AS________',
  options: ['PARALLEL PERSPECTIVE',
      'ANGULAR PERSPECTIVE',
      'ACTUAL PERSPECTIVE',
      'OBLIQUE PERSPECTIVE'],
  correctAnswer: 1,
},

{
  id:'124',
  question: '3-POINT PERSPECTIVE IS ALSO KNOWN AS________',
  options: ['OBLIQUE PERSPECTIVE',
      'ACTUAL PERSPECTIVE',
      'PARALLEL PERSPECTIVE',
      'ANGULAR PERSPECTIVE'],
  correctAnswer: 0,
},

{
  id:'125',
  question: 'THE AREA OF SHUTTER ENCLOSED BETWEEN THE ADJACENT RAILS IS KNOWN AS __________',
  options: ['JAMB',
      'TOP RAIL',
      'SASH',
      'PANEL'],
  correctAnswer: 3,
},

{
  id:'126',
  question: 'THE ENTIRE ASSEMBLY OF STILES, PANEL AND RAILS IS KNOWN AS_________',
  options: ['JAMB',
      'PANEL',
      'SHUTTER',
      'SASH'],
  correctAnswer: 2,
},

{
  id:'127',
  question: 'A VERTICAL MEMBER WHICH IS EMPLOYED TO SUB-DIVIDE A WINDOW OR A DOOR OPENING VERTICALLY IS KNOWN AS ___________.',
  options: ['JAMB',
      'TRANSOM',
      'MULLION',
      'SASH'],
  correctAnswer: 2,
},

{
  id:'128',
  question: 'A HORIZONTAL MEMBER WHICH IS EMPLOYED TO SUB-DIVIDE A WINDOW OPENING HORIZONTALLY IS KNOWN AS ___________.',
  options: ['TRANSOM',
      'SASH',
      'JAMB',
      'MULLION'],
  correctAnswer: 0,
},

{
  id:'129',
  question: 'THE VERTICAL WALL FACE OF AN OPENING WHICH SUPPORTS THE FRAME OF DOOR AND WINDOW IS KNOWN AS  __________.',
  options: ['MULLION',
      'TRANSOM',
      'JAMB',
      'PANEL'],
  correctAnswer: 2,
},

{
  id:'130',
  question: 'DEVELOPMENT OF A CONE IS',
  options: ['RECTANGLE',
      'SPHERE',
      'SECTOR OF CIRCLE',
      'RIGHT ANGLE TRIANGLE'],
  correctAnswer: 2,
},

{
  id:'131',
  question: 'WHEN THE SPACE IS NOT SUFFICIENT FOR QUARTER LANDING STAIRS AND HALF LANDING STAIRS WHICH STAIRS WE PROVIDE?',
  options: ['WINDER STAIRS',
      'PIE STAIRS',
      'ARCHED STAIRS',
      'BOTH A AND B'],
  correctAnswer: 3,
},

{
  id:'132',
  question: 'IN WHICH STAIRS YOU WILL NOT FELL DIZZY WHEN CLIMBING MANY FLOORS?',
  options: ['SPIRAL STAIRS',
      'ARCHED STAIRS',
      'CIRCULAR STAIRS',
      'ELLIPTICAL STAIRS'],
  correctAnswer: 3,
},

{
  id:'133',
  question: 'WHICH ONE IS USED IN LIMITED TO THE COMPRESSIVE MEMBER ONLY?',
  options: ['CAST-IRON',
      'WROUGHT-IRON',
      'PIG-IRON',
      'MILD STEEL'],
  correctAnswer: 0,
},

{
  id:'134',
  question: 'WHICH BAR ARE WIDELY USED AS REINFORCEMENT IN CONCRETE STRUCTURES?',
  options: ['FLAT BARS',
      'ROUND BARS',
      'RIBBED-TOR STEEL BAR',
      'SQUARE BAR'],
  correctAnswer: 2,
},

{
  id:'135',
  question: 'WHICH ONE IS USED TO CONNECT STEEL BEAMS FOR EXTENSION OF THE LENGTH?',
  options: ['EXAPANDED METAL',
      'PLATES',
      'FLAT BARS',
      'ROUND BARS'],
  correctAnswer: 1,
},
{
  id:'136',
  question: 'ISMB STANDS FOR',
  options: ['INDIAN SERVICE MEDIUM BEAMS',
      'INDIAN STANDARD MILD BARS',
      'INDIAN STANDARD MEDIUM BEAMS',
      'INDIAN STANDARD MEDIUM BARS'],
  correctAnswer: 2,
},

{
  id:'137',
  question: 'ISSC STANDS FOR ____________ ',
  options: ['INDIAN STANDARD COLUMN SECTION',
      'INDIAN STANDARD SOFT CHANNEL',
      'INDIAN STANDARD SPECIAL CHAMBER',
      'INDIAN STANDARD SPECIAL CARS'],
  correctAnswer: 0,
},

{
  id:'138',
  question: 'IN STEEL CONSTRUCTION CONNECTING OF ONE RAFTER TO ANOTHER RAFTER IS KNOWN AS____________.',
  options: ['RAFTER',
      'COLUMN',
      'PURLINS',
      'NONE OF THESE'],
  correctAnswer: 1,
},

{
  id:'139',
  question: 'IN PEB STRUCTURE SIDE BRACING ROD MEANS',
  options: ['CONNECTING OF ONE RAFTER TO ANOTHER RAFTER',
      'CONNECTING OF ONE PURLIN TO ANOTHER PURLIN',
      'CONNECTING OF ONE COLUMN TO ANOTHER COLUMN',
      'NONE OF THESE'],
  correctAnswer: 2,
},

{
  id:'140',
  question: 'IN PEB STRUCTURE, ROOF BRACING ROD MEANS',
  options: ['CONNECTING OF ONE COLUMN TO ANOTHER COLUMN',
      'CONNECTING OF ONE RAFTER TO ANOTHER RAFTER',
      'CONNECTING OF ONE PURLIN TO ANOTHER PURLIN',
      'NONE OF THESE'],
  correctAnswer: 1,
},

{
  id:'141',
  question: 'IN PEB STRUCTURE, SAG ROD MEANS__________',
  options: ['CONNECTING OF ONE RAFTER TO ANOTHER RAFTER',
      'CONNECTING OF ONE COLUMN TO ANOTHER COLUMN',
      'CONNECTING OF ONE PURLIN TO ANOTHER PURLIN',
      'NONE OF THESE'],
  correctAnswer: 2,
},

{
  id:'142',
  question: 'THE VERTICAL DISTANCE BETWEEN TWO SUCCESSIVE TREADS IS KNOWN AS _________.',
  options: ['STEP',
      'RISE',
      'RISER',
      'RUN'],
  correctAnswer: 1,
},

{
  id:'143',
  question: 'THE VERTICAL OR FRONT MEMBER OF THE STEP, WHICH IS CONNECTED TO THE TREADS IS KNOWN AS ___________.',
  options: ['RISE',
      'RISER',
      'TREAD',
      'PITCH'],
  correctAnswer: 1,
},

{
  id:'144',
  question: 'THE PROJECTION PART OF TREAD BEYOND THE FACE OF RISER IS KNOWN AS ______________.',
  options: ['SCOTIA',
      'NOISING',
      'PITCH',
      'SOFFIT'],
  correctAnswer: 1,
},

{
  id:'145',
  question: 'WHAT IS THE INTERNAL ANGLE OF OCTAGON?',
  options: ['108',
      '120',
      '135',
      '145'],
  correctAnswer: 2,
},

{
  id:'146',
  question: 'TOTAL ANGLE OF OCTAGON IS ____________________.',
  options: ['360',
      '540',
      '1080',
      '720'],
  correctAnswer: 1,
},
{
  id:'147',
  question: 'WHAT IS THE TOTAL ANGLE OF A PENTAGON?',
  options: ['180',
      '108',
      '480',
      '540'],
  correctAnswer: 2,
},
{
  id:'148',
  question: '1 ACRE = ____________GUNTHA',
  options: ['50',
      '10',
      '40',
      '100'],
  correctAnswer: 2,
},
{
  id:'149',
  question: ' FULL FORM OF RSJ- FULL FORM OF RSJ',
  options: ['ROLLED STEEL JOISTS',
      'ROLLED STEEPLE JOINTS',
      'ROLLING STILL JOINTS',
      'NONE OF THESE'],
  correctAnswer: 0,
},
];


let currentQuestion = 0;
let score = 0;
let userAnswers = [];


function showQuiz() {
  document.getElementById('quiz-container').classList.remove('hidden');
  document.getElementById('score-container').classList.add('hidden');
  renderQuestion();
}

function renderQuestion() {
  const quizContainer = document.getElementById('quiz-container');
  const currentQuestionData = questions[currentQuestion];

  if (currentQuestion < questions.length) {
    // Display question and options
    let optionsHtml = '';
    currentQuestionData.options.forEach((option, index) => {
      optionsHtml += `<label style="color:black">
                        <input style="margin-top:50px" type="radio" name="answer" value="${index}" required>
                        ${option}
                      </label><br>`;
    });

    quizContainer.innerHTML = `<h3 style="color: black;  margin-top: 3rem; font-size:0.85rem">${currentQuestionData.question}</h3>${optionsHtml}
                               <button style="padding:10px 15px; border-radius:10px; font-size:1rem; margin-top:15px" onclick="submitAnswer()" >Submit</button>`;
  } else {
    // Quiz completed, show score
    showScore();
  }
}

function submitAnswer() {
  const selectedOption = document.querySelector('input[name="answer"]:checked');

  if (selectedOption) {
    const userAnswer = parseInt(selectedOption.value);
    userAnswers.push(userAnswer);

    const currentQuestionData = questions[currentQuestion];

    if (userAnswer === currentQuestionData.correctAnswer) {
      score++;
    }

    currentQuestion++;
    renderQuestion();
  }
}

function showScore() {
  document.getElementById('quiz-container').classList.add('hidden');
  const scoreContainer = document.getElementById('score-container');
  scoreContainer.classList.remove('hidden');

  const totalQuestions = questions.length;
  scoreContainer.innerHTML = `<h2 style="text-align:center; margin-bottom:1rem; margin-top:2rem">Quiz Completed</h2>
                              <p style="text-align:center; font-size:0.8rem;
                              font-weight:500; margin-bottom:1rem">Your score: ${score}/${totalQuestions}</p>
                              <button style="margin-left:10px; padding:10px 15px; border-radius:10px; font-size:1rem; margin-top:10px" onclick="showIncorrectAnswers()">View Incorrect Answers</button>
                              <a href="#" onclick="restartQuiz()" style="text-decoration:none; color:rgb(85, 1, 153); font-weight:500" >Restart Quiz</a>`;
}

function showIncorrectAnswers() {
  const scoreContainer = document.getElementById('score-container');
  scoreContainer.innerHTML += `<p style="text-align:center; margin-bottom:1rem; margin-top:1rem;color: rgb(204, 3, 37); font-size:1.2rem">Incorrect Answers:</p>`;

  questions.forEach((question, index) => {
    if (question.correctAnswer !== userAnswers[index]) {
      scoreContainer.innerHTML += `<p style="text-align:center; margin-bottom:1rem; margin-top:1rem; font-size:1.2rem">${question.question}<br>
                                   Your Answer: ${question.options[userAnswers[index]]}<br>
                                   Correct Answer: ${question.options[question.correctAnswer]}</p>`;
    }
  });
}

function restartQuiz() {
  currentQuestion = 0;
  score = 0;
  userAnswers = [];
  const scoreContainer = document.getElementById('score-container');
  scoreContainer.innerHTML = '';
  showQuiz();
}

document.addEventListener('DOMContentLoaded', showQuiz);

